<?php include('components/header.php'); ?>
<?php include('components/navigation.php'); ?>


<div class="container-fluid">
  <div class="col-md-8 mx-auto">
    <h2 class="mt-3">PRIVACY POLICY</h2>
    <p>Last updated: 12/01/2020</p>


    <h3 class="mt-5">Introduction</h3>
    <p>Welcome to Legoto Labs Pvt. Ltd..</p>
    <p>Legoto Labs Pvt. Ltd. (“us”, “we”, or “our”) operates https://superpage.to and Superpage mobile application (hereinafter referred to as “Service”).</p>

    <p>Our Privacy Policy governs your visit to https://superpage.to and Superpage mobile application, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>

    <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>

    <p>Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).</p>

    <h3 class="mt-5">Definitions</h3>
    <p>SERVICE means the https://superpage.to website and Superpage mobile application operated by Legoto Labs Pvt. Ltd..</p>
    <p>PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
    <p>USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
    <p>COOKIES are small files stored on your device (computer or mobile device).</p>
    <p>DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
    <p>DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
    <p>DATA SUBJECT is any living individual who is the subject of Personal Data.</p>
    <p>THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>




  </div>






</div>
<?php include('components/footer.php'); ?>